In [4]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# Placeholders for a tensor that will be always fed. 
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# Cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train =   optimizer.minimize(cost)

# Launch the graph is a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})

    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3064.0815 
Prediction:
 [204.89114 240.39009 239.59418 261.8284  181.6236 ]
10 Cost:  12.938553 
Prediction:
 [156.01439 181.66914 181.72232 198.80847 136.83968]
20 Cost:  12.845003 
Prediction:
 [155.85321 181.50061 181.5432  198.61447 136.71652]
30 Cost:  12.779753 
Prediction:
 [155.83948 181.50922 181.53865 198.61058 136.72847]
40 Cost:  12.714867 
Prediction:
 [155.82623 181.51834 181.53464 198.60727 136.74078]
50 Cost:  12.6503315 
Prediction:
 [155.81302 181.52744 181.53064 198.60397 136.75307]
60 Cost:  12.586145 
Prediction:
 [155.79984 181.53651 181.52666 198.60068 136.7653 ]
70 Cost:  12.5223465 
Prediction:
 [155.78671 181.54556 181.5227  198.59741 136.77753]
80 Cost:  12.458773 
Prediction:
 [155.7736  181.5546  181.51874 198.59413 136.78973]
90 Cost:  12.395579 
Prediction:
 [155.76054 181.56361 181.51479 198.59087 136.8019 ]
100 Cost:  12.332806 
Prediction:
 [155.74751 181.57257 181.51085 198.58762 136.81401]
110 Cost:  12.27032 
Prediction:
 [155.73451 181.581

In [6]:
import tensorflow as tf

x_data = [[73., 93., 89.], [96., 73., 80.], [88., 91., 98.], [66., 75., 93.], [90., 100., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train =   optimizer.minimize(cost)

# Launch the graph is a session
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_data, Y: y_data})

    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  119937.27 
Prediction:
 [[-177.48457 ]
 [-163.08565 ]
 [-175.40663 ]
 [-122.165855]
 [-235.38481 ]]
10 Cost:  280.26532 
Prediction:
 [[167.06084 ]
 [172.5059  ]
 [198.41258 ]
 [193.5926  ]
 [116.046646]]
20 Cost:  269.35327 
Prediction:
 [[167.96751]
 [173.95511]
 [199.49062]
 [194.09172]
 [117.78658]]
30 Cost:  260.39786 
Prediction:
 [[167.74284]
 [174.28569]
 [199.33864]
 [193.56453]
 [118.34749]]
40 Cost:  252.04199 
Prediction:
 [[167.52191]
 [174.60193]
 [199.18796]
 [193.052  ]
 [118.88525]]
50 Cost:  244.24527 
Prediction:
 [[167.30824]
 [174.9078 ]
 [199.04247]
 [192.55698]
 [119.40439]]
60 Cost:  236.97037 
Prediction:
 [[167.1016 ]
 [175.20369]
 [198.902  ]
 [192.07887]
 [119.90553]]
70 Cost:  230.18198 
Prediction:
 [[166.90173]
 [175.48996]
 [198.7664 ]
 [191.61713]
 [120.38936]]
80 Cost:  223.84814 
Prediction:
 [[166.70845]
 [175.76686]
 [198.63548]
 [191.17113]
 [120.85639]]
90 Cost:  217.93787 
Prediction:
 [[166.5215 ]
 [176.03476]
 [198.50908]
 [190.74037]
