In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    # Initialize Tensorflow variables
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # Predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calcualte the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))


0 5.191887 [[-2.0901198   1.1146725   1.5051788 ]
 [-0.46215943 -0.6256517   0.5455881 ]
 [ 0.6881166   1.231295   -2.2705393 ]]
1 3.1364584 [[-2.0698724   1.0590404   1.5405635 ]
 [-0.31644705 -0.8669065   0.6411305 ]
 [ 0.8364465   0.99780715 -2.1853814 ]]
2 2.0724528 [[-2.0986466   1.0547832   1.5735948 ]
 [-0.43205884 -0.8415371   0.7313729 ]
 [ 0.73653996  1.0154992  -2.1031668 ]]
3 1.8180536 [[-2.1017838   1.0267644   1.6047506 ]
 [-0.41325656 -0.9459239   0.8169575 ]
 [ 0.76648754  0.90607977 -2.023695  ]]
4 1.5991962 [[-2.128746    1.0257697   1.6327076 ]
 [-0.52414143 -0.91210186  0.8940203 ]
 [ 0.6682486   0.93005514 -1.9494314 ]]
5 1.4104228 [[-2.1292915   1.0017395   1.6572833 ]
 [-0.4947812  -1.0059249   0.95848316]
 [ 0.7055218   0.82695067 -1.8836001 ]]
6 1.2804351 [[-2.1515565   1.004175    1.6771127 ]
 [-0.58366317 -0.9626085   1.0040487 ]
 [ 0.62253225  0.8570642  -1.8307241 ]]
7 1.2053932 [[-2.149767    0.9875567   1.6919413 ]
 [-0.54185116 -1.0222003   1.0218285 ]
 

In [6]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

# Normalized inputs (min-mx scale)
xy = MinMaxScaler(xy)
print(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  1.9401971 
Prediction:
 [[-1.5818435 ]
 [-0.6219429 ]
 [-0.6865902 ]
 [-0.7739811 ]
 [-0.79093903]
 [-0.76725054]
 [-0.39320326]
 [-0.19230005]]
1 Cost:  1.94006 
Prediction:
 [[-1.5817732 ]
 [-0.62187743]
 [-0.68653554]
 [-0.77393854]
 [-0.79088855]
 [-0.7672019 ]
 [-0.3931716 ]
 [-0.19226986]]
2 Cost:  1.9399226 
Prediction:
 [[-1.581703  ]
 [-0.621812  ]
 [-0.68648076]
 [-0.7738959 ]
 [-0.790838  ]
 [-0.76715314]
 [-0.39313996]
 [-0.19223967]]
3 Cost:  1.9397852 
Prediction:
 [[-1.5816326 ]
 [-0.62174654]
 [-0.6864260