In [2]:
import numpy as np
import tensorflow as tf
import pprint

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [3]:
# Simple Array
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape)  # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [5]:
# 2D Array
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape)  # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [8]:
# Shape, Rank, Axis
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [9]:
t = tf.constant([[1,2], [3,4]])
tf.shape(t).eval()

array([2, 2])

In [10]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [11]:
# Matnul VS Multiply
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [13]:
# Broadcasting: make it work between different shapes 
# It's powerful but you need to know what equations you want to make, otherwise
# the results will be totally different from what you expected.

# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[6., 6.]], dtype=float32)

In [14]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.]])
(matrix1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

In [16]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3. ], [4.]])
(matrix1 + matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

In [20]:
# Reduce mean
tf.reduce_mean([1, 2], axis=0).eval()

x = [[1., 2.], [3., 4.]]

# mean of all elements 
tf.reduce_mean(x).eval()

2.5

In [21]:
# mean of 1 and 3 & 2 and 4 
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [22]:
# mean of 1 and 2 & 3 and 4
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [23]:
# mean of the innermost one which are 1 and 2 & 3 and 4
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [24]:
# Sum
x = [[1., 2.], [3., 4.]]

tf.reduce_sum(x).eval()

10.0

In [25]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [26]:
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

In [31]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [32]:
# Argmax : return index of the largest
x = [[0, 1, 2], [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [33]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [34]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

In [35]:
# Reshape
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
t.shape

(2, 2, 3)

In [36]:
tf.reshape(t, shape=[-1, 3]).eval() 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [38]:
# Reshape (squeeze, expand)
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [39]:
tf.expand_dims([0,1,2],1).eval()

array([[0],
       [1],
       [2]])

In [40]:
# One hot
tf.one_hot([[0],[1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [41]:
t = tf.one_hot([[0],[1],[2],[0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [43]:
# Casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [44]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

In [45]:
# Stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# Ones and Zeros like
x = [[0,1,2],[2,1,0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [50]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
# Zip
for x, y in zip([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [52]:
for x, y, z in zip([1,2,3],[4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
